### ISSUE TITLE
Update JSON files

### ISSUE THREAD

**Issue by slowe** [opnprd/election-2019-collector#10]
- [x] Update live versions
- [x] Fix processing lambda

I've added in the 2017 results breakdown and some demographics to the individual constituency files so you should [grab them all from the constituency directory](https://github.com/odileeds/hexmaps/tree/gh-pages/ge2019/constituencies). I've added a `candidates` array to `2017-06-08` just like we are making for 2019. I've added a `demographics` object at the top level with data about the constituency.

**Comment by slowe** [comment]
@gilesdring Once you've updated the output to include these bits, let me know so that I can work out the +xx% values.

**Comment by gilesdring** [comment]
Errors in all these files...
hexmaps/ge2019/constituencies/E14000711.json
hexmaps/ge2019/constituencies/N06000001.json
hexmaps/ge2019/constituencies/N06000002.json
hexmaps/ge2019/constituencies/N06000003.json
hexmaps/ge2019/constituencies/N06000004.json
hexmaps/ge2019/constituencies/N06000005.json
hexmaps/ge2019/constituencies/N06000006.json
hexmaps/ge2019/constituencies/N06000007.json
hexmaps/ge2019/constituencies/N06000008.json
hexmaps/ge2019/constituencies/N06000009.json
hexmaps/ge2019/constituencies/N06000010.json
hexmaps/ge2019/constituencies/N06000011.json
hexmaps/ge2019/constituencies/N06000012.json
hexmaps/ge2019/constituencies/N06000013.json
hexmaps/ge2019/constituencies/N06000014.json
hexmaps/ge2019/constituencies/N06000015.json
hexmaps/ge2019/constituencies/N06000016.json
hexmaps/ge2019/constituencies/N06000017.json
hexmaps/ge2019/constituencies/N06000018.json
hexmaps/ge2019/constituencies/S14000001.json
hexmaps/ge2019/constituencies/S14000002.json
hexmaps/ge2019/constituencies/S14000003.json
hexmaps/ge2019/constituencies/S14000004.json
hexmaps/ge2019/constituencies/S14000005.json
hexmaps/ge2019/constituencies/S14000006.json
hexmaps/ge2019/constituencies/S14000007.json
hexmaps/ge2019/constituencies/S14000008.json
hexmaps/ge2019/constituencies/S14000009.json
hexmaps/ge2019/constituencies/S14000010.json
hexmaps/ge2019/constituencies/S14000011.json
hexmaps/ge2019/constituencies/S14000012.json
hexmaps/ge2019/constituencies/S14000013.json
hexmaps/ge2019/constituencies/S14000014.json
hexmaps/ge2019/constituencies/S14000015.json
hexmaps/ge2019/constituencies/S14000016.json
hexmaps/ge2019/constituencies/S14000017.json
hexmaps/ge2019/constituencies/S14000018.json
hexmaps/ge2019/constituencies/S14000019.json
hexmaps/ge2019/constituencies/S14000020.json
hexmaps/ge2019/constituencies/S14000021.json
hexmaps/ge2019/constituencies/S14000022.json
hexmaps/ge2019/constituencies/S14000023.json
hexmaps/ge2019/constituencies/S14000024.json
hexmaps/ge2019/constituencies/S14000025.json
hexmaps/ge2019/constituencies/S14000026.json
hexmaps/ge2019/constituencies/S14000027.json
hexmaps/ge2019/constituencies/S14000028.json
hexmaps/ge2019/constituencies/S14000029.json
hexmaps/ge2019/constituencies/S14000030.json
hexmaps/ge2019/constituencies/S14000031.json
hexmaps/ge2019/constituencies/S14000032.json
hexmaps/ge2019/constituencies/S14000033.json
hexmaps/ge2019/constituencies/S14000034.json
hexmaps/ge2019/constituencies/S14000035.json
hexmaps/ge2019/constituencies/S14000036.json
hexmaps/ge2019/constituencies/S14000037.json
hexmaps/ge2019/constituencies/S14000038.json
hexmaps/ge2019/constituencies/S14000039.json
hexmaps/ge2019/constituencies/S14000040.json
hexmaps/ge2019/constituencies/S14000041.json
hexmaps/ge2019/constituencies/S14000042.json
hexmaps/ge2019/constituencies/S14000043.json
hexmaps/ge2019/constituencies/S14000044.json
hexmaps/ge2019/constituencies/S14000045.json
hexmaps/ge2019/constituencies/S14000046.json
hexmaps/ge2019/constituencies/S14000047.json
hexmaps/ge2019/constituencies/S14000048.json
hexmaps/ge2019/constituencies/S14000049.json
hexmaps/ge2019/constituencies/S14000050.json
hexmaps/ge2019/constituencies/S14000051.json
hexmaps/ge2019/constituencies/S14000052.json
hexmaps/ge2019/constituencies/S14000053.json
hexmaps/ge2019/constituencies/S14000054.json
hexmaps/ge2019/constituencies/S14000055.json
hexmaps/ge2019/constituencies/S14000056.json
hexmaps/ge2019/constituencies/S14000057.json
hexmaps/ge2019/constituencies/S14000058.json
hexmaps/ge2019/constituencies/S14000059.json

**Comment by gilesdring** [comment]
Most are missing demographic data parse error: Invalid string: control characters from U+0000 through U+001F must be escaped at line 65, column 25
hexmaps/ge2019/constituencies/E14000711.json

**Comment by gilesdring** [comment]
@slowe Issues above. I'll work on fixing in the processing so we have a complete cycle...
