### ISSUE TITLE
Negative numbers

### ISSUE THREAD

**Issue by patricklake2** [opnprd/election-2019-collector#3]
Allows you to submit results with negative numbers 
<img width="471" alt="Screenshot 2019-12-06 at 10 34 23" src="https://user-images.githubusercontent.com/52745289/70316629-075a6a80-1814-11ea-96b0-d06812034255.png">
<img width="631" alt="Screenshot 2019-12-06 at 10 33 46" src="https://user-images.githubusercontent.com/52745289/70316630-075a6a80-1814-11ea-8387-8c8ecc808ba9.png">

**Comment by gilesdring** [comment]
Have added fix in develop branch which prevents adding negative numbers.
